import LoginForm from '@/Components/LoginForm';
import { Spin } from 'antd';
import Head from 'next/head';
import { useSelector } from 'react-redux';

export default function Home() {
  const loading = useSelector((state) => state.user.loading);

  return (
    <>
      <Head>
        <title>Redux Toolkit Post Request</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {loading ? <Spin size="large" tip="Loading"></Spin> : <LoginForm />}
      </div>
    </>
  );
}
